### ISSUE TITLE
stale environments in drop down for environments

### ISSUE THREAD

**Issue by corporate-gadfly** [skx/puppet-summary#72] opened 2020-05-02 21:03 UTC
The environments feature was recently contributed in #54. I use puppet with [r10k](https://github.com/puppetlabs/r10k) which encourages the use of throw-away environments as a means of promoting fast feature development and continuous integration _(by creating git branches)_.

As an example, I had a throw-away environment called `agent` which I was using to do some feature development for installing agents.
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/1200537/80892064-4fcc6600-8c96-11ea-831c-6becd10d0f45.png">

Once I was satisfied with the Git branch for `agent`, I merged it into `production`. After that, I deleted `agent` Git branch in my puppet control repository. At its next run, `r10k` automatically removed the `agent` environment.

What consideration should be given to "throw-away" environments?

**Comment by skx** [comment] 2020-05-19 15:40
I'm sorry for not getting back to you sooner, I had hoped that @plazonic, who implemented this support in #71 would comment.

I suspect the solution here is to have a cron-job prune obsolete environments, whether integrated into the core or as a new flag for the report-pruning.

Would that suit your needs do you think?  (I appreciate there would still be a period of time where the orphaned branch/environment were visible, but I think that this is the simplest solution to implement.)

**Comment by plazonic** [comment] 2020-05-19 15:52
Oh, sorry, not looking at this that often, tagging works though... 

I don't see how this could be done automatically - how is puppet summary supposed to know that an environment is obsolete? There is already an option for prune command that will remove obsoleted reports but which of those are in environments that can go away and which ones are relevant and should be kept?

I suppose it wouldn't be hard to add a prune option for choosing entire environments to remove but you'd then somehow to automate that (e.g. at the time you delete environment you'd have to also issue a prune command).

**Comment by skx** [comment] 2020-05-19 16:01
Now you say that I've looked at the database and you're right; I had thought there was a separate table, so we could run "DELETE FROM environments WHERE $used=0".

But as you suggest, if there is a report with an environment it'll stay until pruned.

I suspect this is a "wontfix" / "cantfix", or adding a manual "-prune-env=testing/x"

**Comment by corporate-gadfly** [comment] 2020-05-19 16:03
@plazonic , @skx Thanks for commenting.

I could manually delete environments and/or try to add a post-hook to `r10k`.

**Comment by skx** [comment] 2020-05-19 16:06
I could imagine:

```
$ ./puppet-summary  prune -environment="foo"
```

Which would just run:

```
SQL>  UPDATE reports SET environment='' WHERE environment='foo'
```

**Comment by plazonic** [comment] 2020-05-19 16:17
Probably better if it were a bit more generic, i.e. if --environment="foo" was given to then restrict all specified prune ops to just that environment.  One could then combine that with days 0 to prune it all (I think, not sure what happens if days is set to 0).

**Comment by corporate-gadfly** [comment] 2020-05-19 16:31
I may be overthinking my "original ask".

The only issue that I have at the moment is that I have un-pruned reports in my puppet-summary `reports` directory, but no way to reach them, since the environment has been deleted.

Does that make sense? So, e.g.:
```
[root@gems-mgmt-syscfg-1 reports]# tree -L 1 /etc/puppetlabs/code/environments/
/etc/puppetlabs/code/environments/
└── production

1 directory, 0 files
```
So, there is only `production` environment, but in my `puppet-summary` reports directory, I have 4 reports for a single host with environment `legato`:
```
[root@gems-mgmt-syscfg-1 reports]# grep -rl 'environment: legato' .
./easi-sh2-uat-rxpws-1.fqdn/96071da26932820e87cf6e12c8c2b9ea4d2f43c4
./easi-sh2-uat-rxpws-1.fqdn/aa416bcb2d972cc0fd9b8762d8f1a62bca1a1cf9
./easi-sh2-uat-rxpws-1.fqdn/e76e01ddf350006e466d754e9c19cbf161389213
./easi-sh2-uat-rxpws-1.fqdn/0b2149f5d0f02cb8897fb52f2e085308cef4e4cb
```
Yet, when I go to `puppet-summary` to look at `legato`, I don't see anything:
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/1200537/82352836-91fee280-99cc-11ea-8912-2260aa4053e8.png">
Any way to see those orphaned reports?

I think eventually, they will drop off _(after the 30 day prune)_??

**Comment by plazonic** [comment] 2020-05-19 17:11
I don't know that they will drop off - if they are not shown in the interface then they are not in the db but it wouldn't hurt to verify.  E.g.

sqlite3 /path/to/db/ps.db
select * from reports where environment='legato';

You haven't maybe ran prune with wrong reports dir or something similar?

**Comment by plazonic** [comment] 2020-05-19 20:23
I also wrote a bit of code to check for "dangling" yaml report files - i.e. ones that are not referred to in the database.  That should help here too.  I should probably wait before I push that commit or it might get mixed up with the previous pull request?

**Comment by corporate-gadfly** [comment] 2020-05-19 20:32
> sqlite3 /path/to/db/ps.db
select * from reports where environment='legato';

Sorry, I got sidetracked. The result of the SQL reported the identical 4 reports from the previous comment.
```1958|easi-sh2-uat-rxpws-1|failed|easi-sh2-uat-rxpws-1./0b2149f5d0f02cb8897fb52f2e085308cef4e4cb|13.590671818|1588094655|272|3|1|0|legato
1959|easi-sh2-uat-rxpws-1|changed|easi-sh2-uat-rxpws-1./96071da26932820e87cf6e12c8c2b9ea4d2f43c4|18.73729137|1588094729|272|0|0|1|legato
1961|easi-sh2-uat-rxpws-1|unchanged|easi-sh2-uat-rxpws-1/aa416bcb2d972cc0fd9b8762d8f1a62bca1a1cf9|16.857331314|1588094883|272|0|0|0|legato
1962|easi-sh2-uat-rxpws-1|changed|easi-sh2-uat-rxpws-1/e76e01ddf350006e466d754e9c19cbf161389213|41.500788158|1588095283|272|0|0|2|legato
```

**Comment by corporate-gadfly** [comment] 2020-05-19 20:43
To summarize:

1. There is only one **real** environment, `production`
1. There are orphaned environments which are shown in the dropdown. There are files present in the `reports` directory referencing these orphaned environments. There are entries present in the database referencing these orphaned environments
1. When selecting the orphaned environment from the dropdown, no reports are shown

**Comment by plazonic** [comment] 2020-05-19 21:39
Indeed, graph would be empty too if it wasn't finding these entries. And as this is quite long ago it would have to be on the orphaned tab (which I assume you clicked on and is empty as well)?  Is this node listed on the main page (listing all environments), under orphaned nodes?

I see nothing obviously wrong in the code - any errors in puppet-summary logs? How about if you add to the URL "?accept=application/json" - should make it dump any nodes as json or null if it doesn't find any (so ..../environment/legato?accept=application/json).  This would exclude page templating being at fault.

**Comment by corporate-gadfly** [comment] 2020-05-19 22:14
- All tabs are empty when looking at orphaned environment
- That particular node **does** appear under all environments and has timings and report entries
![image](https://user-images.githubusercontent.com/1200537/82383761-757a9e80-99fc-11ea-943a-43d63a1b0833.png)
```
# curl -i -H "Accept: application/json" http://localhost:3001/environment/legato
HTTP/1.1 200 OK
Content-Type: application/json
Date: Tue, 19 May 2020 22:05:40 GMT
Content-Length: 4

null
```
`journalctl` for `puppet-summary` service shows only HTTP access log style entries. Would I see errors there as well? Nothing in there looks like an error.

**Comment by corporate-gadfly** [comment] 2020-05-19 23:04
This particular node has a lot of reports, so it looks like I'm hitting a maximum of 50 for reports _(see #74 )_, however, I'm able to see the report from the orphaned environment by going to its specific URL. E.g.: http://localhost:3001/report/1958

**Comment by plazonic** [comment] 2020-05-20 03:26
OK, I see what the problem is - mea culpa - filter for environments really should have been part of the sql query.  I also saw I was missing environment filter in sql queries used for producing graph stats (so numbers shown were way too big).

Fixed both in pending pull as well as added more pruning options.

**Closed** 2020-05-20 05:12 UTC
Labels: enhancement

**Comment by skx** [comment] 2020-05-20 05:13
PR merged, so I'm going to hope this is resolved now.  Thanks to @corporate-gadfly for your patience, and @plazonic for being willing and able to resolve the problems :)

There is the pending issue of 50-reports shown by default, which I'lll look at shortly.  I'm actually amazed nobody spotted that until now!

**Comment by corporate-gadfly** [comment] 2020-05-20 18:33
Brilliant and confirmed. As expected, most nodes are showing up under `Orphaned` tab.
![image](https://user-images.githubusercontent.com/1200537/82483669-c47d0e00-9aa6-11ea-8b4b-185f6a27a618.png)

**Comment by skx** [comment] 2020-05-22 08:36
Available now:

* https://github.com/skx/puppet-summary/releases/tag/release-1.8
